FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80

# Comando com docs explícitos habilitados
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80", "--docs-url", "/docs", "--redoc-url", "/redoc"]
